import Link from "next/link";
import { ArrowRight, BarChart3, Car, Eye, GraduationCap, Route, Scale, SearchCheck } from "lucide-react";
import { ModelCard } from "@/components/model-card";

const assessments = [
  { title: "Public transport strength", icon: Route, tone: "green" as const, question: "How practical is it to get around without driving?", summary: "Uses the available route evidence to assess walking access, bus coverage, MRT reach and route resilience.", inputs: ["Walking access to stops and stations", "Bus-route coverage and scheduled frequency", "MRT reach and interchange access", "Alternative route options"] },
  { title: "Driving connectivity", icon: Car, tone: "blue" as const, question: "How practical is it to get around by car?", summary: "Combines road access, routed journeys where available, route connectivity and nearby HDB parking evidence.", inputs: ["Major-road access", "Traffic-aware routing when a route is available", "Route connectivity", "Nearby HDB carpark evidence"] },
  { title: "Fair-price estimate", icon: BarChart3, tone: "purple" as const, question: "What does recent comparable evidence suggest about value?", summary: "Produces a defensible estimated range from relevant resale transactions and confirmed property characteristics when sufficient evidence exists.", inputs: ["Comparable resale transactions", "Town or location", "Flat type, floor area and remaining lease", "Storey evidence when available"] },
  { title: "School access", icon: GraduationCap, tone: "orange" as const, question: "What nearby-school distance evidence is available?", summary: "Measures proximity to the reference school data and groups results into practical distance bands.", inputs: ["Property-to-school distance", "Nearby primary and secondary schools", "Distance bands", "Selected named-school distances when matched"] },
];

export default function HowFlatsAreEvaluatedPage() {
  return <div className="nh-page-grid py-12 sm:py-16">
    <section className="grid gap-10 lg:grid-cols-[0.95fr_0.75fr] lg:items-end"><div><p className="nh-section-kicker">Methodology</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.04em] text-blue-950 sm:text-5xl">How NearHome evaluates flats</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">NearHome uses separate, purpose-built assessments for the factors that matter. Each result includes its inputs, interpretation and limitations so the comparison is not based on a single unexplained number.</p></div><div className="rounded-3xl border border-blue-100 bg-blue-50 p-6"><Eye className="text-blue-700" size={28} /><p className="mt-3 font-semibold text-blue-950">Evidence, not a black box</p><p className="mt-2 text-sm leading-6 text-slate-600">When a data source is unavailable or insufficient, NearHome shows that plainly rather than substituting a score.</p></div></section>
    <section className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{assessments.map((assessment) => <ModelCard key={assessment.title} title={assessment.title} icon={assessment.icon} tone={assessment.tone} description={assessment.summary} detailsHref={`#${assessment.title.toLowerCase().replaceAll(" ", "-")}`} />)}</section>
    <section className="mt-16"><p className="nh-section-kicker">Inputs at a glance</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-blue-950">What goes into each assessment</h2><p className="mt-3 text-slate-600">The exact result depends on the available evidence for each listing.</p><div className="mt-8 grid gap-4 lg:grid-cols-2">{assessments.map((assessment) => { const Icon = assessment.icon; return <article id={assessment.title.toLowerCase().replaceAll(" ", "-")} key={assessment.title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><Icon size={21} /></span><div><h3 className="font-semibold text-blue-950">{assessment.title}</h3><p className="text-sm text-slate-600">{assessment.question}</p></div></div><ul className="mt-5 space-y-2.5">{assessment.inputs.map((input) => <li key={input} className="flex gap-3 rounded-lg border border-slate-100 bg-slate-50 px-3 py-2.5 text-sm text-slate-700"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-blue-600" aria-hidden="true" />{input}</li>)}</ul></article>})}</div></section>
    <section className="mt-16"><h2 className="text-3xl font-bold tracking-tight text-blue-950">How to interpret the results</h2><div className="mt-7 grid gap-5 md:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-6"><BarChart3 className="text-blue-700" /><h3 className="mt-4 text-lg font-semibold text-blue-950">Compare consistently</h3><p className="mt-2 text-sm leading-6 text-slate-600">Use factor-level results to compare the same evidence across your shortlisted flats. A score is only shown where the model calculated one.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><Scale className="text-blue-700" /><h3 className="mt-4 text-lg font-semibold text-blue-950">Review trade-offs</h3><p className="mt-2 text-sm leading-6 text-slate-600">The leading flat may not lead on every factor. Read the comparisons alongside your selected priorities and the displayed context.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><SearchCheck className="text-blue-700" /><h3 className="mt-4 text-lg font-semibold text-blue-950">Inspect evidence and limits</h3><p className="mt-2 text-sm leading-6 text-slate-600">Open each assessment to review available sources, calculation details and any missing-data limitations.</p></article></div></section>
    <section className="mt-16 rounded-3xl border border-blue-100 bg-blue-50/60 p-6 sm:p-8"><h2 className="text-2xl font-bold text-blue-950">Technical notes</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">These summaries describe the active product behaviour. They are deliberately high-level: each real comparison shows the specific evidence and limitations that applied.</p><div className="mt-6 divide-y divide-blue-100 overflow-hidden rounded-2xl border border-blue-100 bg-white">{assessments.map((assessment) => <details key={assessment.title} className="group p-5"><summary className="cursor-pointer list-none font-semibold text-blue-950"><span className="flex items-center justify-between gap-4">{assessment.title}<span aria-hidden="true" className="text-blue-700 transition group-open:rotate-45">+</span></span></summary><div className="mt-4 text-sm leading-6 text-slate-600"><p><strong className="text-slate-800">Purpose:</strong> {assessment.question}</p><p className="mt-2"><strong className="text-slate-800">Output:</strong> {assessment.summary}</p><p className="mt-2"><strong className="text-slate-800">Missing data:</strong> Where the required evidence cannot be obtained, the comparison marks the assessment as unavailable or insufficient rather than creating a substitute result.</p></div></details>)}</div><Link href="/" className="nh-primary mt-7">Start comparing your flats <ArrowRight className="ml-2" size={16} /></Link></section>
  </div>;
}
