import Link from "next/link";
import { ArrowRight, CheckCircle2, ClipboardPaste, FilePenLine, Link2, ListChecks, MessageSquareText, Search, SlidersHorizontal } from "lucide-react";
import { MarketingPreview } from "@/components/marketing-preview";

const faqs = [
  ["How many flats can I compare?", "NearHome supports a shortlist of two to five confirmed flats."],
  ["How long does enrichment take?", "A full enrichment commonly takes one to two minutes. Availability depends on the underlying data sources."],
  ["Can I edit a flat after adding it?", "You can review and edit extracted fields before you confirm a Smart Paste listing. You can also remove a confirmed flat from the shortlist."],
  ["Why might a listing URL fail?", "Some listing websites restrict automated retrieval. Pasting the listing text is the most reliable way to use Smart Paste."],
  ["Does school proximity guarantee admission?", "No. NearHome reports available proximity evidence only; it does not assess admission eligibility or placement."],
];

export default function HowItWorksPage() {
  return <div className="nh-page-grid py-12 sm:py-16">
    <section className="max-w-3xl"><p className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1.5 text-sm font-semibold text-blue-700"><CheckCircle2 size={16} /> Simple, transparent and data-backed</p><h1 className="mt-5 text-4xl font-bold tracking-[-0.04em] text-blue-950 sm:text-5xl">How NearHome works</h1><p className="mt-4 text-lg leading-8 text-slate-600">Compare your shortlisted flats in a few simple steps and make a more informed decision.</p></section>
    <ol className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[[Search, "Shortlist flats", "Find flats you like on the property portals you prefer."], [ClipboardPaste, "Add your flats", "Use listing text, a listing URL where accessible, or manual entry."], [SlidersHorizontal, "Select priorities", "Choose the factors that deserve the most attention in your comparison."], [ListChecks, "Compare results", "Review factor-level results, trade-offs and available evidence."]].map(([Icon, title, description], index) => { const StepIcon = Icon as typeof Search; return <li key={String(title)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="grid h-9 w-9 place-items-center rounded-full bg-blue-700 text-sm font-bold text-white">{index + 1}</span><StepIcon className="mt-5 text-blue-700" size={25} /><h2 className="mt-3 text-lg font-semibold text-blue-950">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{String(description)}</p></li>})}</ol>
    <section className="mt-16"><div className="text-center"><h2 className="text-3xl font-bold tracking-tight text-blue-950">What you’ll see in the final comparison</h2><p className="mt-3 text-slate-600">Clear context and evidence, based on the data that could be calculated.</p></div><div className="mt-8 grid gap-5 lg:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-6"><FilePenLine className="text-blue-700" /><h3 className="mt-4 text-lg font-semibold text-blue-950">Property details and context</h3><p className="mt-2 text-sm leading-6 text-slate-600">See the confirmed details you entered alongside key price, size and lease information.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><ListChecks className="text-blue-700" /><h3 className="mt-4 text-lg font-semibold text-blue-950">Supported factor results</h3><p className="mt-2 text-sm leading-6 text-slate-600">Compare transport, driving, fair-price, school and journey results where available.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><MessageSquareText className="text-blue-700" /><h3 className="mt-4 text-lg font-semibold text-blue-950">Evidence behind each result</h3><p className="mt-2 text-sm leading-6 text-slate-600">Open the existing breakdowns to understand the inputs, source data and limitations.</p></article></div></section>
    <section className="mt-16 grid gap-8 rounded-3xl border border-blue-100 bg-blue-50/60 p-6 lg:grid-cols-[0.9fr_1.1fr] lg:p-8"><div><h2 className="text-2xl font-bold text-blue-950">Add flats your way</h2><p className="mt-3 text-slate-600">Pasting listing text is recommended because source websites may block URL retrieval.</p><div className="mt-6 space-y-3 text-sm text-slate-700"><p className="flex items-center gap-3"><ClipboardPaste className="text-blue-700" size={18} />Paste listing text <span className="rounded-full bg-blue-100 px-2 py-0.5 text-xs font-semibold text-blue-700">Recommended</span></p><p className="flex items-center gap-3"><Link2 className="text-blue-700" size={18} />Paste listing URL</p><p className="flex items-center gap-3"><FilePenLine className="text-blue-700" size={18} />Enter manually</p></div><Link href="/" className="nh-primary mt-7">Start comparing <ArrowRight className="ml-2" size={16} /></Link></div><MarketingPreview compact /></section>
    <section className="mt-16"><h2 className="text-2xl font-bold text-blue-950">Frequently asked questions</h2><div className="mt-5 divide-y divide-slate-200 overflow-hidden rounded-2xl border border-slate-200 bg-white">{faqs.map(([question, answer]) => <details key={question} className="group p-5"><summary className="cursor-pointer list-none font-semibold text-blue-950 focus:outline-none"><span className="flex items-center justify-between gap-4">{question}<span aria-hidden="true" className="text-blue-700 transition group-open:rotate-45">+</span></span></summary><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{answer}</p></details>)}</div></section>
  </div>;
}
