steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - apps/api/Dockerfile
      - --build-arg
      - GIT_SHA=${_GIT_SHA}
      - --tag
      - ${_IMAGE}
      - .

substitutions:
  _GIT_SHA: "unknown"

images:
  - ${_IMAGE}
